DROP DATABASE IF EXISTS dashboardly;

CREATE DATABASE dashboardly;

USE dashboardly;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(60) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  avatarUrl VARCHAR(1000)
);

CREATE TABLE sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL ,
  token VARCHAR(100) NOT NULL UNIQUE,
  FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE boards (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ownerId INT NOT NULL,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(100),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  isListed BOOL NOT NULL DEFAULT 1,
  FOREIGN KEY (ownerId) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE bookmarks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  boardId INT NOT NULL,
  title VARCHAR(50) NOT NULL,
  url VARCHAR(1000) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  description VARCHAR(1000),
  FOREIGN KEY (boardId) REFERENCES boards (id) ON DELETE CASCADE
);
